---
name: Baby Buddy
version: 1.12.2
homeassistant: 2022.8.1
slug: baby_buddy
description: Track sleep, feedings, diaper changes, tummy time and more!
url: https://github.com/OttPeterR/addon-babybuddy
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
panel_icon: hass:baby-bottle
ingress: true
ingress_port: 1337
ingress_stream: false
panel_admin: false
options:
  CSRF_TRUSTED_ORIGINS: ""
schema: 
  CSRF_TRUSTED_ORIGINS: str
ports:
 8000/tcp: null
